global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'eureka-server'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['eureka-server:8761']

  - job_name: 'config-server'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['config-server:8888']

  - job_name: 'api-gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['api-gateway:8080']

  - job_name: 'ingest-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['ingest-service:8081']

  - job_name: 'transparency-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['transparency-service:8082']

  - job_name: 'notification-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['notification-service:8083']

  - job_name: 'demo-traffic-generator'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['demo-traffic-generator:8084']
