dependencies {
    implementation 'io.micrometer:micrometer-registry-prometheus'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation 'org.springframework.cloud:spring-cloud-starter-netflix-eureka-client'
    implementation 'org.springframework.cloud:spring-cloud-starter-config'
    implementation 'org.springframework.kafka:spring-kafka'
    implementation 'org.springframework.cloud:spring-cloud-starter-circuitbreaker-resilience4j'
    implementation 'com.stripe:stripe-java:29.1.0'
    implementation 'com.google.auth:google-auth-library-oauth2-http:1.52.0'
    implementation 'com.google.api-client:google-api-client:2.9.1'
    implementation 'com.google.apis:google-api-services-gmail:v1-rev20260525-2.0.0'
    implementation 'jakarta.mail:jakarta.mail-api:2.1.5'
    implementation 'org.eclipse.angus:angus-mail:2.0.5'
    testImplementation 'org.springframework.kafka:spring-kafka-test'
}
